db:
  type: "sqlite" #pgsql, sqlite
  uri: 'file:E:\GoProjects\learning\mis-catanddog\repos\sqlite3\db.sqlite'#"postgresql://user:secret@host:5432/repo"
  timeout: 1000
  initDB: false
web:
  port: 8080
  timeout: 4000
  idleTimeout: 60000
log:
  level: "debug"
  format: "text"